[2018-05-29 22:12:35,412] {models.py:167} INFO - Filling up the DagBag from /home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/second.py
[2018-05-29 22:12:36,031] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run second node_n2 2018-05-29T22:12:05.074249 --job_id 15 --raw -sd DAGS_FOLDER/second.py']
[2018-05-29 22:12:36,237] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:12:36,237] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-29 22:12:36,461] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:12:36,461] {models.py:167} INFO - Filling up the DagBag from /home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/second.py
[2018-05-29 22:12:36,899] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:12:36,899] {models.py:1126} INFO - Dependencies all met for <TaskInstance: second.node_n2 2018-05-29 22:12:05.074249 [queued]>
[2018-05-29 22:12:36,902] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:12:36,902] {models.py:1126} INFO - Dependencies all met for <TaskInstance: second.node_n2 2018-05-29 22:12:05.074249 [queued]>
[2018-05-29 22:12:36,902] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:12:36,902] {models.py:1318} INFO - 
[2018-05-29 22:12:36,902] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-29 22:12:36,902] {base_task_runner.py:95} INFO - Subtask: Starting attempt 1 of 1
[2018-05-29 22:12:36,902] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-29 22:12:36,902] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-29 22:12:37,012] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:12:37,012] {models.py:1342} INFO - Executing <Task(PythonOperator): node_n2> on 2018-05-29 22:12:05.074249
[2018-05-29 22:12:37,032] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:12:37,031] {models.py:1417} ERROR - name 'context' is not defined
[2018-05-29 22:12:37,032] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-29 22:12:37,032] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/models.py", line 1374, in run
[2018-05-29 22:12:37,032] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-29 22:12:37,032] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-29 22:12:37,032] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-29 22:12:37,032] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/second.py", line 58, in execute_query
[2018-05-29 22:12:37,033] {base_task_runner.py:95} INFO - Subtask:     inputs[x] = context['task_instance'].xcom_pull(task_ids=mapp[0],key=mapp[1])
[2018-05-29 22:12:37,033] {base_task_runner.py:95} INFO - Subtask: NameError: name 'context' is not defined
[2018-05-29 22:12:37,033] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:12:37,032] {models.py:1441} INFO - Marking task as FAILED.
[2018-05-29 22:12:37,162] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:12:37,161] {models.py:1462} ERROR - name 'context' is not defined
[2018-05-29 22:12:37,162] {base_task_runner.py:95} INFO - Subtask: /home/db1/anaconda3/lib/python3.6/site-packages/airflow/utils/helpers.py:406: DeprecationWarning: Importing PythonOperator directly from <module 'airflow.operators' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/__init__.py'> has been deprecated. Please import from '<module 'airflow.operators' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/__init__.py'>.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
[2018-05-29 22:12:37,162] {base_task_runner.py:95} INFO - Subtask:   DeprecationWarning)
[2018-05-29 22:12:37,162] {base_task_runner.py:95} INFO - Subtask: /home/db1/anaconda3/lib/python3.6/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: DeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-29 22:12:37,163] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-29 22:12:37,164] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-29 22:12:37,164] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/bin/airflow", line 28, in <module>
[2018-05-29 22:12:37,165] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-29 22:12:37,165] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-29 22:12:37,165] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-29 22:12:37,165] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-29 22:12:37,165] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-29 22:12:37,165] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/models.py", line 1374, in run
[2018-05-29 22:12:37,165] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-29 22:12:37,166] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-29 22:12:37,166] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-29 22:12:37,166] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/second.py", line 58, in execute_query
[2018-05-29 22:12:37,166] {base_task_runner.py:95} INFO - Subtask:     inputs[x] = context['task_instance'].xcom_pull(task_ids=mapp[0],key=mapp[1])
[2018-05-29 22:12:37,166] {base_task_runner.py:95} INFO - Subtask: NameError: name 'context' is not defined
[2018-05-29 22:12:41,047] {jobs.py:2083} INFO - Task exited with return code 1
