[2018-05-29 22:16:46,707] {models.py:167} INFO - Filling up the DagBag from /home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/second.py
[2018-05-29 22:16:47,235] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run second node_n2 2018-05-29T22:16:14.240135 --job_id 17 --raw -sd DAGS_FOLDER/second.py']
[2018-05-29 22:16:47,438] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:47,438] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-29 22:16:47,663] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:47,663] {models.py:167} INFO - Filling up the DagBag from /home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/second.py
[2018-05-29 22:16:48,045] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,045] {models.py:1126} INFO - Dependencies all met for <TaskInstance: second.node_n2 2018-05-29 22:16:14.240135 [queued]>
[2018-05-29 22:16:48,048] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,048] {models.py:1126} INFO - Dependencies all met for <TaskInstance: second.node_n2 2018-05-29 22:16:14.240135 [queued]>
[2018-05-29 22:16:48,048] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,048] {models.py:1318} INFO - 
[2018-05-29 22:16:48,048] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-29 22:16:48,048] {base_task_runner.py:95} INFO - Subtask: Starting attempt 1 of 1
[2018-05-29 22:16:48,048] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-29 22:16:48,048] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-29 22:16:48,174] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,174] {models.py:1342} INFO - Executing <Task(PythonOperator): node_n2> on 2018-05-29 22:16:14.240135
[2018-05-29 22:16:48,214] {base_task_runner.py:95} INFO - Subtask: ========================================
[2018-05-29 22:16:48,214] {base_task_runner.py:95} INFO - Subtask: Executing query  q4
[2018-05-29 22:16:48,214] {base_task_runner.py:95} INFO - Subtask: {'hash': None}
[2018-05-29 22:16:48,215] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,214] {connection.py:449} INFO - ~~ [CONNECT] ('127.0.0.1', 7687)
[2018-05-29 22:16:48,215] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,214] {connection.py:486} INFO - ~~ [SECURE] 127.0.0.1
[2018-05-29 22:16:48,235] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,235] {connection.py:516} INFO - C: [HANDSHAKE] 0x6060B017 [1, 0, 0, 0]
[2018-05-29 22:16:48,236] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,236] {connection.py:541} INFO - S: [HANDSHAKE] 1
[2018-05-29 22:16:48,237] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,237] {connection.py:209} INFO - C: INIT ('neo4j-python/1.3.1', {'scheme': 'basic', 'principal': 'neo4j', 'credentials': 'password'})
[2018-05-29 22:16:48,238] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,238] {connection.py:270} INFO - S: SUCCESS ({'server': 'Neo4j/3.2.6'})
[2018-05-29 22:16:48,239] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,239] {connection.py:449} INFO - ~~ [CONNECT] ('127.0.0.1', 7687)
[2018-05-29 22:16:48,239] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,239] {connection.py:486} INFO - ~~ [SECURE] 127.0.0.1
[2018-05-29 22:16:48,256] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,256] {connection.py:516} INFO - C: [HANDSHAKE] 0x6060B017 [1, 0, 0, 0]
[2018-05-29 22:16:48,258] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,258] {connection.py:541} INFO - S: [HANDSHAKE] 1
[2018-05-29 22:16:48,258] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,258] {connection.py:209} INFO - C: INIT ('neo4j-python/1.3.1', {'scheme': 'basic', 'principal': 'neo4j', 'credentials': 'password'})
[2018-05-29 22:16:48,260] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,260] {connection.py:270} INFO - S: SUCCESS ({'server': 'Neo4j/3.2.6'})
[2018-05-29 22:16:48,260] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,260] {connection.py:199} INFO - C: RUN ('UNWIND {hash} AS hash_value\r\nMATCH (u :USER) -[:TWEETED]-> (t :TWEET), (t) -[:HAS_HASHTAG]-> (:HASHTAG {text:hash_value})\r\nWITH DISTINCT u\r\nMATCH (u) -[:TWEETED]-> (t1 :TWEET)\r\nRETURN u.id,count(t1)', {'hash': None})
[2018-05-29 22:16:48,260] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,260] {connection.py:201} INFO - C: PULL_ALL ()
[2018-05-29 22:16:48,503] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,503] {connection.py:270} INFO - S: SUCCESS ({'result_available_after': 242, 'fields': ['u.id', 'count(t1)']})
[2018-05-29 22:16:48,504] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,503] {models.py:1417} ERROR - name 'outputs' is not defined
[2018-05-29 22:16:48,504] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-29 22:16:48,504] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/models.py", line 1374, in run
[2018-05-29 22:16:48,504] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-29 22:16:48,504] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-29 22:16:48,504] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-29 22:16:48,504] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/second.py", line 66, in execute_query
[2018-05-29 22:16:48,504] {base_task_runner.py:95} INFO - Subtask:     ret = {x:[] for x in outputs}
[2018-05-29 22:16:48,504] {base_task_runner.py:95} INFO - Subtask: NameError: name 'outputs' is not defined
[2018-05-29 22:16:48,504] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,504] {models.py:1441} INFO - Marking task as FAILED.
[2018-05-29 22:16:48,623] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,623] {models.py:1462} ERROR - name 'outputs' is not defined
[2018-05-29 22:16:48,623] {base_task_runner.py:95} INFO - Subtask: /home/db1/anaconda3/lib/python3.6/site-packages/airflow/utils/helpers.py:406: DeprecationWarning: Importing PythonOperator directly from <module 'airflow.operators' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/__init__.py'> has been deprecated. Please import from '<module 'airflow.operators' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/__init__.py'>.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
[2018-05-29 22:16:48,624] {base_task_runner.py:95} INFO - Subtask:   DeprecationWarning)
[2018-05-29 22:16:48,624] {base_task_runner.py:95} INFO - Subtask: /home/db1/anaconda3/lib/python3.6/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: DeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-29 22:16:48,624] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-29 22:16:48,624] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-29 22:16:48,625] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/bin/airflow", line 28, in <module>
[2018-05-29 22:16:48,625] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-29 22:16:48,625] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-29 22:16:48,625] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-29 22:16:48,625] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-29 22:16:48,625] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-29 22:16:48,625] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/models.py", line 1374, in run
[2018-05-29 22:16:48,625] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-29 22:16:48,625] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-29 22:16:48,625] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-29 22:16:48,625] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/second.py", line 66, in execute_query
[2018-05-29 22:16:48,625] {base_task_runner.py:95} INFO - Subtask:     ret = {x:[] for x in outputs}
[2018-05-29 22:16:48,625] {base_task_runner.py:95} INFO - Subtask: NameError: name 'outputs' is not defined
[2018-05-29 22:16:48,663] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,663] {connection.py:338} INFO - ~~ [CLOSE]
[2018-05-29 22:16:48,663] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 22:16:48,663] {connection.py:338} INFO - ~~ [CLOSE]
[2018-05-29 22:16:52,321] {jobs.py:2083} INFO - Task exited with return code 1
