[2018-05-29 18:20:08,293] {models.py:167} INFO - Filling up the DagBag from /home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/example.py
[2018-05-29 18:20:09,024] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run example query.q6 2018-05-29T18:20:05.118862 --job_id 8 --raw -sd DAGS_FOLDER/example.py']
[2018-05-29 18:20:09,221] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:20:09,221] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-29 18:20:09,445] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:20:09,445] {models.py:167} INFO - Filling up the DagBag from /home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/example.py
[2018-05-29 18:20:09,798] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:20:09,797] {models.py:1126} INFO - Dependencies all met for <TaskInstance: example.query.q6 2018-05-29 18:20:05.118862 [queued]>
[2018-05-29 18:20:09,798] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:20:09,798] {models.py:1126} INFO - Dependencies all met for <TaskInstance: example.query.q6 2018-05-29 18:20:05.118862 [queued]>
[2018-05-29 18:20:09,799] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:20:09,798] {models.py:1318} INFO - 
[2018-05-29 18:20:09,799] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-29 18:20:09,799] {base_task_runner.py:95} INFO - Subtask: Starting attempt 1 of 1
[2018-05-29 18:20:09,799] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-29 18:20:09,799] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-29 18:20:09,922] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:20:09,921] {models.py:1342} INFO - Executing <Task(PythonOperator): query.q6> on 2018-05-29 18:20:05.118862
[2018-05-29 18:20:09,941] {base_task_runner.py:95} INFO - Subtask: (13, 'q7', 'MATCH(n) RETURN COUNT(n)', 'neo4j')
[2018-05-29 18:20:09,941] {base_task_runner.py:95} INFO - Subtask: ['id_', 'counts']
[2018-05-29 18:20:09,941] {base_task_runner.py:95} INFO - Subtask: ========================================
[2018-05-29 18:20:09,941] {base_task_runner.py:95} INFO - Subtask: Executing query  q7
[2018-05-29 18:20:09,941] {base_task_runner.py:95} INFO - Subtask: {}
[2018-05-29 18:20:09,941] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:20:09,939] {models.py:1417} ERROR - name 'GraphDatabase' is not defined
[2018-05-29 18:20:09,942] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-29 18:20:09,942] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/models.py", line 1374, in run
[2018-05-29 18:20:09,942] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-29 18:20:09,942] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-29 18:20:09,942] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-29 18:20:09,942] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/example.py", line 47, in execute_query
[2018-05-29 18:20:09,942] {base_task_runner.py:95} INFO - Subtask:     driver = GraphDatabase.driver("bolt://localhost:7687", auth=basic_auth("neo4j", "password"))
[2018-05-29 18:20:09,942] {base_task_runner.py:95} INFO - Subtask: NameError: name 'GraphDatabase' is not defined
[2018-05-29 18:20:09,942] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:20:09,941] {models.py:1441} INFO - Marking task as FAILED.
[2018-05-29 18:20:10,063] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 18:20:10,063] {models.py:1462} ERROR - name 'GraphDatabase' is not defined
[2018-05-29 18:20:10,063] {base_task_runner.py:95} INFO - Subtask: /home/db1/anaconda3/lib/python3.6/site-packages/airflow/utils/helpers.py:406: DeprecationWarning: Importing PythonOperator directly from <module 'airflow.operators' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/__init__.py'> has been deprecated. Please import from '<module 'airflow.operators' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/__init__.py'>.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
[2018-05-29 18:20:10,064] {base_task_runner.py:95} INFO - Subtask:   DeprecationWarning)
[2018-05-29 18:20:10,064] {base_task_runner.py:95} INFO - Subtask: /home/db1/anaconda3/lib/python3.6/site-packages/airflow/utils/helpers.py:406: DeprecationWarning: Importing DbApiHook directly from <module 'airflow.hooks' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/hooks/__init__.py'> has been deprecated. Please import from '<module 'airflow.hooks' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/hooks/__init__.py'>.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
[2018-05-29 18:20:10,064] {base_task_runner.py:95} INFO - Subtask:   DeprecationWarning)
[2018-05-29 18:20:10,064] {base_task_runner.py:95} INFO - Subtask: /home/db1/anaconda3/lib/python3.6/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: DeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-29 18:20:10,064] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-29 18:20:10,065] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-29 18:20:10,065] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/bin/airflow", line 28, in <module>
[2018-05-29 18:20:10,066] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-29 18:20:10,066] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-29 18:20:10,066] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-29 18:20:10,066] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-29 18:20:10,066] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-29 18:20:10,066] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/models.py", line 1374, in run
[2018-05-29 18:20:10,066] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-29 18:20:10,066] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-29 18:20:10,066] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-29 18:20:10,067] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/example.py", line 47, in execute_query
[2018-05-29 18:20:10,067] {base_task_runner.py:95} INFO - Subtask:     driver = GraphDatabase.driver("bolt://localhost:7687", auth=basic_auth("neo4j", "password"))
[2018-05-29 18:20:10,067] {base_task_runner.py:95} INFO - Subtask: NameError: name 'GraphDatabase' is not defined
[2018-05-29 18:20:13,961] {jobs.py:2083} INFO - Task exited with return code 1
