[2018-05-29 17:55:27,208] {models.py:167} INFO - Filling up the DagBag from /home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/example.py
[2018-05-29 17:55:27,757] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run example query.q6 2018-05-29T17:55:23.349755 --job_id 6 --raw -sd DAGS_FOLDER/example.py']
[2018-05-29 17:55:27,955] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:55:27,955] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-29 17:55:28,179] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:55:28,179] {models.py:167} INFO - Filling up the DagBag from /home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/example.py
[2018-05-29 17:55:28,564] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:55:28,564] {models.py:1126} INFO - Dependencies all met for <TaskInstance: example.query.q6 2018-05-29 17:55:23.349755 [queued]>
[2018-05-29 17:55:28,565] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:55:28,565] {models.py:1126} INFO - Dependencies all met for <TaskInstance: example.query.q6 2018-05-29 17:55:23.349755 [queued]>
[2018-05-29 17:55:28,565] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:55:28,565] {models.py:1318} INFO - 
[2018-05-29 17:55:28,565] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-29 17:55:28,565] {base_task_runner.py:95} INFO - Subtask: Starting attempt 1 of 1
[2018-05-29 17:55:28,565] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-29 17:55:28,565] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-29 17:55:28,793] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:55:28,793] {models.py:1342} INFO - Executing <Task(PythonOperator): query.q6> on 2018-05-29 17:55:23.349755
[2018-05-29 17:55:28,811] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:55:28,810] {models.py:1417} ERROR - conn_name_attr is not defined
[2018-05-29 17:55:28,812] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-29 17:55:28,812] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/models.py", line 1374, in run
[2018-05-29 17:55:28,812] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-29 17:55:28,813] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-29 17:55:28,813] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-29 17:55:28,813] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/example.py", line 21, in execute_query
[2018-05-29 17:55:28,813] {base_task_runner.py:95} INFO - Subtask:     hook = DbApiHook()
[2018-05-29 17:55:28,813] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/hooks/dbapi_hook.py", line 43, in __init__
[2018-05-29 17:55:28,814] {base_task_runner.py:95} INFO - Subtask:     raise AirflowException("conn_name_attr is not defined")
[2018-05-29 17:55:28,814] {base_task_runner.py:95} INFO - Subtask: airflow.exceptions.AirflowException: conn_name_attr is not defined
[2018-05-29 17:55:28,814] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:55:28,812] {models.py:1441} INFO - Marking task as FAILED.
[2018-05-29 17:55:28,943] {base_task_runner.py:95} INFO - Subtask: [2018-05-29 17:55:28,942] {models.py:1462} ERROR - conn_name_attr is not defined
[2018-05-29 17:55:28,943] {base_task_runner.py:95} INFO - Subtask: /home/db1/anaconda3/lib/python3.6/site-packages/airflow/utils/helpers.py:406: DeprecationWarning: Importing PythonOperator directly from <module 'airflow.operators' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/__init__.py'> has been deprecated. Please import from '<module 'airflow.operators' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/__init__.py'>.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
[2018-05-29 17:55:28,943] {base_task_runner.py:95} INFO - Subtask:   DeprecationWarning)
[2018-05-29 17:55:28,944] {base_task_runner.py:95} INFO - Subtask: /home/db1/anaconda3/lib/python3.6/site-packages/airflow/utils/helpers.py:406: DeprecationWarning: Importing DbApiHook directly from <module 'airflow.hooks' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/hooks/__init__.py'> has been deprecated. Please import from '<module 'airflow.hooks' from '/home/db1/anaconda3/lib/python3.6/site-packages/airflow/hooks/__init__.py'>.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
[2018-05-29 17:55:28,944] {base_task_runner.py:95} INFO - Subtask:   DeprecationWarning)
[2018-05-29 17:55:28,944] {base_task_runner.py:95} INFO - Subtask: /home/db1/anaconda3/lib/python3.6/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: DeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-29 17:55:28,944] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-29 17:55:28,946] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-29 17:55:28,946] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/bin/airflow", line 28, in <module>
[2018-05-29 17:55:28,946] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-29 17:55:28,946] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-29 17:55:28,947] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-29 17:55:28,947] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-29 17:55:28,947] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-29 17:55:28,947] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/models.py", line 1374, in run
[2018-05-29 17:55:28,947] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-29 17:55:28,948] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-29 17:55:28,948] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-29 17:55:28,948] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/Documents/TwitterAnalytics/dashboard_website/myapp/airflow/dags/example.py", line 21, in execute_query
[2018-05-29 17:55:28,948] {base_task_runner.py:95} INFO - Subtask:     hook = DbApiHook()
[2018-05-29 17:55:28,949] {base_task_runner.py:95} INFO - Subtask:   File "/home/db1/anaconda3/lib/python3.6/site-packages/airflow/hooks/dbapi_hook.py", line 43, in __init__
[2018-05-29 17:55:28,949] {base_task_runner.py:95} INFO - Subtask:     raise AirflowException("conn_name_attr is not defined")
[2018-05-29 17:55:28,949] {base_task_runner.py:95} INFO - Subtask: airflow.exceptions.AirflowException: conn_name_attr is not defined
[2018-05-29 17:55:32,764] {jobs.py:2083} INFO - Task exited with return code 1
